version: '3.8'  # Adjust version as per your Docker Engine version compatibility

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_manager
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data  # Corrected typo in volume path
    networks:
      - task-manager-network

  task-manager-backend:
    container_name: task-manager-backend
    image: task_manager/v1
    ports:
      - "9099:9090"
    networks:
      - task-manager-network
    depends_on:
      - postgres

volumes:
  postgres:

networks:
  task-manager-network:
    driver: bridge